# System Info Now Configuration File
output:
  format: json # Only json is currently supported
  directory: output
  filename: system_data.json

logging:
  level: INFO
  directory: logs

# Customizable root directory path for project 
# specific context gathering used by language 
# collectors
project:
  root_dir: "." # Default to current directory, can be set to absolute path

collectors:
  # Core system information - recommended to keep enabled
  system: true
  
  # Language-specific collectors - disabled by default
  # WARNING: When feeding data to LLMs, the complex structure with many versions, 
  # paths, and package details in these collectors may cause hallucinations.
  # Only enable if you specifically need this language data.
  python: false
  javascript: false
  